version: '3.7'

services:
  database:
    image: mysql:5.7

    container_name: babaydar_db

    environment:

      MYSQL_ROOT_PASSWORD: p123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: babaydar
      MYSQL_PASSWORD: babaydar_123

    networks:
      - mynet


  myapp:
    image: babaydar/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - 80:80
    networks:
      - mynet

networks:
  mynet:
    driver: bridge



